### ISSUE TITLE
running from localhost

### ISSUE THREAD

**Issue by pihentagy** [cotoami/cotoami#125]
When running `mix phx.server`, I get an infinite loop:
```
> cotoami@1.0.0 watch /home/pihentagy/utils/cotoami/assets
> NPM_BIN=$(npm bin) brunch watch --stdin

sh: 1: brunch: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! cotoami@1.0.0 watch: `NPM_BIN=$(npm bin) brunch watch --stdin`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the cotoami@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pihentagy/.npm/_logs/2019-01-17T12_35_32_205Z-debug.log
[error] Task #PID<0.493.0> started from CotoamiWeb.Endpoint terminating
** (stop) :watcher_command_error
    (phoenix) lib/phoenix/endpoint/watcher.ex:29: Phoenix.Endpoint.Watcher.watch/3
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &Phoenix.Endpoint.Watcher.watch/3
    Args: ["npm", ["run", "watch"], [cd: "/home/pihentagy/utils/cotoami/assets"]]
```

**Comment by pihentagy** [comment]
Any advice how can I improve this bug report?

**Comment by pihentagy** [comment]
The mentioned log contains:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'watch' ]
2 info using npm@6.8.0
3 info using node@v11.10.0
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle cotoami@1.0.0~prewatch: cotoami@1.0.0
6 info lifecycle cotoami@1.0.0~watch: cotoami@1.0.0
7 verbose lifecycle cotoami@1.0.0~watch: unsafe-perm in lifecycle true
8 verbose lifecycle cotoami@1.0.0~watch: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pihentagy/utils/cotoami/assets/node_modules/.bin:/home/pihentagy/.asdf/installs/erlang/20.0/erts-9.0/bin:/home/pihentagy/.asdf/installs/erlang/20.0/bin:/home/pihentagy/.asdf/shims:/home/pihentagy/.asdf/bin:/home/pihentagy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/pihentagy/bin
9 verbose lifecycle cotoami@1.0.0~watch: CWD: /home/pihentagy/utils/cotoami/assets
10 silly lifecycle cotoami@1.0.0~watch: Args: [ '-c', 'NPM_BIN=$(npm bin) brunch watch --stdin' ]
11 info lifecycle cotoami@1.0.0~watch: Failed to exec watch script
12 verbose stack Error: cotoami@1.0.0 watch: `NPM_BIN=$(npm bin) brunch watch --stdin`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:197:13)
12 verbose stack     at maybeClose (internal/child_process.js:984:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
13 verbose pkgid cotoami@1.0.0
14 verbose cwd /home/pihentagy/utils/cotoami/assets
15 verbose Linux 4.15.0-45-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "watch"
17 verbose node v11.10.0
18 verbose npm  v6.8.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error cotoami@1.0.0 watch: `NPM_BIN=$(npm bin) brunch watch --stdin`
23 error spawn ENOENT
24 error Failed at the cotoami@1.0.0 watch script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by marubinotto** [comment]
Sorry for the lack of documentation. Actually, you need to execute the following commands to launch the app with `mix phx.server`:

```
$ cd assets
$ npm install
$ cd ../
$ mix deps.get
$ mix phx.server
```

**Comment by pihentagy** [comment]
Thanks, it helped in a way, but still not complete. Now after the `mix phx.server` I get:

```
[error] backend port not found: :inotifywait

[info] Running CotoamiWeb.Endpoint with Cowboy using http://0.0.0.0:4000
[info] Running migrations on start...
[info] Already up

> cotoami@1.0.0 watch /home/pihentagy/utils/cotoami/assets
> NPM_BIN=$(npm bin) brunch watch --stdin

Elm compile: src/Main.elm, in elm, to ../vendor/elm.js
-- NO elm.json FILE ------------------------------------------------------------

It looks like you are starting a new Elm project. Very exciting! Try running:

    elm init

It will help you get set up. It is really simple!

12:04:34 - error: Compiling of elm/src/Main.elm failed. Error: Command failed: /home/pihentagy/utils/cotoami/assets/node_modules/.bin/elm make --debug --output ../vendor/elm.js src/Main.elm
   -- NO elm.json FILE ------------------------------------------------------------
   
   It looks like you are starting a new Elm project. Very exciting! Try running:
   
       elm init
   
   It will help you get set up. It is really simple!
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
12:04:34 - info: compiled 243 files into 2 files, copied 22 in 3.2 sec
```

After that navigating to localhost:4000 gives me a blank page. And some logs:
```
Stack trace was suppressed. Run with `LOGGY_STACKS=1` to see the trace. 
12:04:34 - info: compiled 243 files into 2 files, copied 22 in 3.2 sec
[info] Header 'x-cotoami-client-id' does not exist
[debug] Processing with CotoamiWeb.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] state=set duration=67.585 status=200 params={} path=/ method=GET format=html controller=CotoamiWeb.PageController action=index request_id=2m39d9u4k5db41s7og0000a2
```

**Comment by marubinotto** [comment]
It appears that your Elm version is not compatible with Cotoami's version (probably yours is 0.19). That is strange because the version is specified by the project configuration.

Could you execute the following command and tell me the output?

```
$ /home/pihentagy/utils/cotoami/assets/node_modules/.bin/elm --version
```

And, what happens if you get the latest code of Cotoami freshly and do the same thing?

**Comment by pihentagy** [comment]
```
pihentagy@thinkpad:~$ /home/pihentagy/utils/cotoami/assets/node_modules/.bin/elm --version
0.19.0
```

Checking out current head solved the problem.

Now I need to figure out the correct email address to login.

**Comment by marubinotto** [comment]
I've added a new way to launch Cotoami with Docker. Just one single command:

```
$ wget -qO - https://raw.githubusercontent.com/cotoami/cotoami/master/launch/run.sh | bash
```

See also:
https://github.com/cotoami/cotoami#launch-your-own-server-with-docker

**Comment by marubinotto** [comment]
@pihentagy If you don't need to touch the source code, I recommend the one single command solution above. It provides default configuration so you can start using it immediately.

**Comment by pihentagy** [comment]
Cool, it works with some glitches:

```
pihentagy@thinkpad:~$ wget -qO - https://raw.githubusercontent.com/cotoami/cotoami/master/launch/run.sh | bash
bash: line 6: docker-machine: command not found
```

It continues and works.

The URLs doesn't contain hostname, and I got URLs like:
```
Hello!

Here’s the link you requested to get into Cotoami:

http://:4000/signin/onljcb5jdq9h1j028tn3o5g04abm92q38i0nu2d3cq38s5cg

For your security, this link expires in 10 minutes and can only be used once.

- The Cotoami Team.
```

**Comment by marubinotto** [comment]
@pihentagy The command failed to get the docker host address. What kind of docker setup do you use?

**Comment by pihentagy** [comment]
> What kind of docker setup do you use?

I don't know what do you mean. I am not a docker expert.

**Comment by marubinotto** [comment]
@pihentagy What OS do you use? And how did you install Docker?

**Comment by pihentagy** [comment]
I have linux mint and installed docker with package magager.

**Comment by marubinotto** [comment]
@pihentagy I see. I modified the launch script, so could you try the following commands?

```
$ export COMPOSE_PROJECT_NAME=cotoami && docker-compose stop && docker-compose rm -f
$ wget -qO - https://raw.githubusercontent.com/cotoami/cotoami/develop/launch/run.sh | bash
```

**Comment by pihentagy** [comment]
It works, thanks.
